#!/bin/bash

: "${AIO_API="\"https://aioapi.seceurity.place\""}"
: "${AIO_APILEN=$((${#AIO_API}-2))}"

gcc -o aio-cli \
    -Wall \
    -std=c99\
    -D"AIO_API=${AIO_API}" -D"AIO_APILEN=${AIO_APILEN}"\
    -O2\
    `pkg-config --libs --cflags json-c vips libcurl libsixel` -lselector\
    "$@" ./**/*.c ./*.c
